### ISSUE TITLE
Generator script does not produce correct values for 1 and 4 components

### ISSUE THREAD

**Issue by theagentd** [kecho/CircularDofFilterGenerator#3]
Hello! Excellent presentation on GDC!

While implementing your separable DoF technique, I encountered some issues with the Python script. The generator works perfectly for component counts 2, 3, and 5, but there seems to be an issue with the (a, b, A, B) constants for component counts 1 and 4.

While I was able to reproduce the images of the real and imaginary components of the 2-component circular blur in your GDC presentation, but I was unable to reproduce the images for a 1-component blur. I noticed that the constants you use for the 1-component blur in circulardof.pdf were different than the ones specified in the Python script, and implementing them into the script fixes the generator for 1-component blurs:

```
    if c == 1:
        #P = [[ -0.548794, 0.411259, 5.268909, -0.886528  ]]
        P = [[ 1.624835, -0.862325, 0.767583, 1.862321  ]] #new constants
```

That fixes the 1-component blur and I am getting the same results as in your GDC presentation! However, I am not sure what is wrong with the 4-component blur. Since my shader code works fine for 1, 2, 3 and 4-component blurs, I am pretty sure that it's not a bug on my end.

Thank you for your time!

**Comment by theagentd** [comment]
I see now that there's already a pull request for a fix of the 1-component blur. However, the 4-component blur remains an open issue.

**Comment by kecho** [comment]
I totally missed this @theagentd 
I fixed the 1 component, thanks a lot! will try 4 component soon
